version: '3.5'
services:
  mongodb:
   image: mongo
   restart: always
   container_name: mongodb
   env_file:
   - ./.env
   ports:
    - '27017:27017'
   volumes:
    - ./mongodb:/data-db
  
  mongodb-express:
   image: mongo-express
   restart: always
   container_name: mongo-express
   env_file:
   - ./.env
   ports:
    - 8081:8081
  